import { NetflixIcon } from "@/components/icons/netflix-icon";
import { YouTubeIcon } from "@/components/icons/youtube-icon";
import { ViuIcon } from "@/components/icons/viu-icon";
import { WeTVIcon } from "@/components/icons/wetv-icon";
import { IQIYIIcon } from "@/components/icons/iqiyi-icon";
import { OneDIcon } from "@/components/icons/oned-icon";
import { TrueIDIcon } from "@/components/icons/trueid-icon";
import type { SubscriptionService, OfferGroup } from "@/lib/types";

export const subscriptionServices: SubscriptionService[] = [
  { id: 'viu', name: 'Viu', logo: ViuIcon, description: 'Asian dramas, movies, and originals.', plans: [{ id: 'viu-premium', name: 'Premium', price: 119, features: ['Ad-free', 'Full HD'] }] },
  { id: 'wetv', name: 'WeTV', logo: WeTVIcon, description: 'Binge-watch original & exclusive content.', plans: [{ id: 'wetv-vip', name: 'VIP', price: 139, features: ['Ad-free', 'Early access'] }] },
  { id: 'iqiyi', name: 'iQIYI VIP Standard', logo: IQIYIIcon, description: 'Popular Asian dramas, variety shows, and animes.', plans: [{ id: 'iqiyi-standard', name: 'VIP Standard', price: 119, features: ['Full HD', '2 screens'] }] },
  { id: 'oned', name: 'oneD', logo: OneDIcon, description: 'Thai dramas and exclusive content.', plans: [{ id: 'oned-premium', name: 'Premium', price: 59, features: ['Ad-free', 'Early access'] }] },
  { id: 'trueplus', name: 'True Plus', logo: TrueIDIcon, description: 'Movies, series, and sports from True.', plans: [{ id: 'trueplus-monthly', name: 'Monthly', price: 199, features: ['Live TV', 'VOD content'] }] },
  { id: 'trueidshort', name: 'True ID Short', logo: TrueIDIcon, description: 'Short-form video content from True ID.', plans: [{ id: 'trueidshort-access', name: 'Access', price: 49, features: ['Exclusive short clips'] }] },
  { id: 'youtube', name: 'YouTube Premium', logo: YouTubeIcon, description: 'Ad-free YouTube and YouTube Music.', plans: [{ id: 'yt-premium', name: 'Premium', price: 179, features: ['Ad-free', 'Background play'] }] },
  { id: 'netflix-mobile', name: 'Netflix Mobile', logo: NetflixIcon, description: 'Watch on your mobile device.', plans: [{ id: 'n-mobile', name: 'Mobile', price: 99, features: ['480p', 'Mobile/Tablet'] }] },
  { id: 'netflix-basic', name: 'Netflix Basic', logo: NetflixIcon, description: 'Basic plan for all devices.', plans: [{ id: 'n-basic', name: 'Basic', price: 169, features: ['720p', 'All devices'] }] },
  { id: 'netflix-standard', name: 'Netflix Standard', logo: NetflixIcon, description: 'Standard HD plan.', plans: [{ id: 'n-standard', name: 'Standard', price: 349, features: ['1080p', '2 screens'] }] },
  { id: 'netflix-premium', name: 'Netflix Premium', logo: NetflixIcon, description: 'Premium 4K+HDR plan.', plans: [{ id: 'n-premium', name: 'Premium', price: 419, features: ['4K+HDR', '4 screens'] }] },
];

export const offerGroups: OfferGroup[] = [
  // Standalone
  { id: 'offerGroup1', packName: 'Viu', services: ['viu'], fullPrice: 119, sellingPrice: 119 },
  { id: 'offerGroup2', packName: 'WeTV', services: ['wetv'], fullPrice: 139, sellingPrice: 139 },
  { id: 'offerGroup3', packName: 'iQIYI VIP Standard', services: ['iqiyi'], fullPrice: 119, sellingPrice: 119 },
  { id: 'offerGroup4', packName: 'oneD', services: ['oned'], fullPrice: 59, sellingPrice: 59 },
  { id: 'offerGroup5', packName: 'True Plus', services: ['trueplus'], fullPrice: 199, sellingPrice: 199 },
  { id: 'offerGroup6', packName: 'True ID Short', services: ['trueidshort'], fullPrice: 49, sellingPrice: 49 },
  { id: 'offerGroup7', packName: 'YouTube Premium', services: ['youtube'], fullPrice: 179, sellingPrice: 179 },
  { id: 'offerGroup8', packName: 'Netflix mobile', services: ['netflix-mobile'], fullPrice: 99, sellingPrice: 99 },
  { id: 'offerGroup9', packName: 'Netflix Basic', services: ['netflix-basic'], fullPrice: 169, sellingPrice: 169 },
  { id: 'offerGroup10', packName: 'Netflix Standard', services: ['netflix-standard'], fullPrice: 349, sellingPrice: 349 },
  { id: 'offerGroup11', packName: 'Netflix Premium', services: ['netflix-premium'], fullPrice: 419, sellingPrice: 419 },

  // Pack1 - 2 services - 119 THB
  { id: 'offerGroup12', packName: 'Pack 1', services: ['viu', 'wetv'], fullPrice: 258, sellingPrice: 119 },
  { id: 'offerGroup13', packName: 'Pack 1', services: ['viu', 'iqiyi'], fullPrice: 238, sellingPrice: 119 },
  { id: 'offerGroup14', packName: 'Pack 1', services: ['viu', 'oned'], fullPrice: 178, sellingPrice: 119 },
  { id: 'offerGroup15', packName: 'Pack 1', services: ['viu', 'trueplus'], fullPrice: 318, sellingPrice: 119 },
  { id: 'offerGroup16', packName: 'Pack 1', services: ['viu', 'trueidshort'], fullPrice: 168, sellingPrice: 119 },
  { id: 'offerGroup17', packName: 'Pack 1', services: ['viu', 'netflix-mobile'], fullPrice: 218, sellingPrice: 119 },
  { id: 'offerGroup18', packName: 'Pack 1', services: ['wetv', 'iqiyi'], fullPrice: 258, sellingPrice: 119 },
  { id: 'offerGroup19', packName: 'Pack 1', services: ['wetv', 'oned'], fullPrice: 198, sellingPrice: 119 },
  { id: 'offerGroup20', packName: 'Pack 1', services: ['wetv', 'trueplus'], fullPrice: 338, sellingPrice: 119 },
  { id: 'offerGroup21', packName: 'Pack 1', services: ['wetv', 'trueidshort'], fullPrice: 188, sellingPrice: 119 },
  { id: 'offerGroup22', packName: 'Pack 1', services: ['wetv', 'netflix-mobile'], fullPrice: 238, sellingPrice: 119 },
  { id: 'offerGroup23', packName: 'Pack 1', services: ['iqiyi', 'oned'], fullPrice: 178, sellingPrice: 119 },
  { id: 'offerGroup24', packName: 'Pack 1', services: ['iqiyi', 'trueplus'], fullPrice: 318, sellingPrice: 119 },
  { id: 'offerGroup25', packName: 'Pack 1', services: ['iqiyi', 'trueidshort'], fullPrice: 168, sellingPrice: 119 },
  { id: 'offerGroup26', packName: 'Pack 1', services: ['iqiyi', 'netflix-mobile'], fullPrice: 218, sellingPrice: 119 },
  { id: 'offerGroup27', packName: 'Pack 1', services: ['oned', 'trueplus'], fullPrice: 258, sellingPrice: 119 },
  { id: 'offerGroup28', packName: 'Pack 1', services: ['oned', 'trueidshort'], fullPrice: 108, sellingPrice: 119 },
  { id: 'offerGroup29', packName: 'Pack 1', services: ['oned', 'netflix-mobile'], fullPrice: 158, sellingPrice: 119 },
  { id: 'offerGroup30', packName: 'Pack 1', services: ['trueplus', 'trueidshort'], fullPrice: 248, sellingPrice: 119 },
  { id: 'offerGroup31', packName: 'Pack 1', services: ['trueplus', 'netflix-mobile'], fullPrice: 298, sellingPrice: 119 },
  { id: 'offerGroup32', packName: 'Pack 1', services: ['trueidshort', 'netflix-mobile'], fullPrice: 148, sellingPrice: 119 },

  // Pack2 - 3 services - 229 THB
  { id: 'offerGroup33', packName: 'Pack 2', services: ['viu', 'wetv', 'netflix-mobile'], fullPrice: 357, sellingPrice: 229 },
  { id: 'offerGroup34', packName: 'Pack 2', services: ['viu', 'wetv', 'netflix-basic'], fullPrice: 427, sellingPrice: 229 },
  { id: 'offerGroup35', packName: 'Pack 2', services: ['viu', 'wetv', 'youtube'], fullPrice: 437, sellingPrice: 229 },
  { id: 'offerGroup36', packName: 'Pack 2', services: ['viu', 'iqiyi', 'netflix-mobile'], fullPrice: 337, sellingPrice: 229 },
  { id: 'offerGroup37', packName: 'Pack 2', services: ['viu', 'iqiyi', 'netflix-basic'], fullPrice: 407, sellingPrice: 229 },
  { id: 'offerGroup38', packName: 'Pack 2', services: ['viu', 'iqiyi', 'youtube'], fullPrice: 417, sellingPrice: 229 },
  { id: 'offerGroup39', packName: 'Pack 2', services: ['viu', 'oned', 'netflix-mobile'], fullPrice: 277, sellingPrice: 229 },
  { id: 'offerGroup40', packName: 'Pack 2', services: ['viu', 'oned', 'netflix-basic'], fullPrice: 347, sellingPrice: 229 },
  { id: 'offerGroup41', packName: 'Pack 2', services: ['viu', 'oned', 'youtube'], fullPrice: 357, sellingPrice: 229 },
  { id: 'offerGroup42', packName: 'Pack 2', services: ['viu', 'trueplus', 'netflix-mobile'], fullPrice: 417, sellingPrice: 229 },
  { id: 'offerGroup43', packName: 'Pack 2', services: ['viu', 'trueplus', 'netflix-basic'], fullPrice: 487, sellingPrice: 229 },
  { id: 'offerGroup44', packName: 'Pack 2', services: ['viu', 'trueplus', 'youtube'], fullPrice: 497, sellingPrice: 229 },
  { id: 'offerGroup45', packName: 'Pack 2', services: ['viu', 'trueidshort', 'netflix-mobile'], fullPrice: 267, sellingPrice: 229 },
  { id: 'offerGroup46', packName: 'Pack 2', services: ['viu', 'trueidshort', 'netflix-basic'], fullPrice: 337, sellingPrice: 229 },
  { id: 'offerGroup47', packName: 'Pack 2', services: ['viu', 'trueidshort', 'youtube'], fullPrice: 347, sellingPrice: 229 },
  { id: 'offerGroup48', packName: 'Pack 2', services: ['wetv', 'iqiyi', 'netflix-mobile'], fullPrice: 357, sellingPrice: 229 },
  { id: 'offerGroup49', packName: 'Pack 2', services: ['wetv', 'iqiyi', 'netflix-basic'], fullPrice: 427, sellingPrice: 229 },
  { id: 'offerGroup50', packName: 'Pack 2', services: ['wetv', 'iqiyi', 'youtube'], fullPrice: 437, sellingPrice: 229 },
  { id: 'offerGroup51', packName: 'Pack 2', services: ['wetv', 'oned', 'netflix-mobile'], fullPrice: 297, sellingPrice: 229 },
  { id: 'offerGroup52', packName: 'Pack 2', services: ['wetv', 'oned', 'netflix-basic'], fullPrice: 367, sellingPrice: 229 },
  { id: 'offerGroup53', packName: 'Pack 2', services: ['wetv', 'oned', 'youtube'], fullPrice: 377, sellingPrice: 229 },
  { id: 'offerGroup54', packName: 'Pack 2', services: ['wetv', 'trueplus', 'netflix-mobile'], fullPrice: 437, sellingPrice: 229 },
  { id: 'offerGroup55', packName: 'Pack 2', services: ['wetv', 'trueplus', 'netflix-basic'], fullPrice: 507, sellingPrice: 229 },
  { id: 'offerGroup56', packName: 'Pack 2', services: ['wetv', 'trueplus', 'youtube'], fullPrice: 517, sellingPrice: 229 },
  { id: 'offerGroup57', packName: 'Pack 2', services: ['wetv', 'trueidshort', 'netflix-mobile'], fullPrice: 287, sellingPrice: 229 },
  { id: 'offerGroup58', packName: 'Pack 2', services: ['wetv', 'trueidshort', 'netflix-basic'], fullPrice: 357, sellingPrice: 229 },
  { id: 'offerGroup59', packName: 'Pack 2', services: ['wetv', 'trueidshort', 'youtube'], fullPrice: 367, sellingPrice: 229 },
  { id: 'offerGroup60', packName: 'Pack 2', services: ['iqiyi', 'oned', 'netflix-mobile'], fullPrice: 277, sellingPrice: 229 },
  { id: 'offerGroup61', packName: 'Pack 2', services: ['iqiyi', 'oned', 'netflix-basic'], fullPrice: 347, sellingPrice: 229 },
  { id: 'offerGroup62', packName: 'Pack 2', services: ['iqiyi', 'oned', 'youtube'], fullPrice: 357, sellingPrice: 229 },
  { id: 'offerGroup63', packName: 'Pack 2', services: ['iqiyi', 'trueplus', 'netflix-mobile'], fullPrice: 417, sellingPrice: 229 },
  { id: 'offerGroup64', packName: 'Pack 2', services: ['iqiyi', 'trueplus', 'netflix-basic'], fullPrice: 487, sellingPrice: 229 },
  { id: 'offerGroup65', packName: 'Pack 2', services: ['iqiyi', 'trueplus', 'youtube'], fullPrice: 497, sellingPrice: 229 },
  { id: 'offerGroup66', packName: 'Pack 2', services: ['iqiyi', 'trueidshort', 'netflix-mobile'], fullPrice: 267, sellingPrice: 229 },
  { id: 'offerGroup67', packName: 'Pack 2', services: ['iqiyi', 'trueidshort', 'netflix-basic'], fullPrice: 337, sellingPrice: 229 },
  { id: 'offerGroup68', packName: 'Pack 2', services: ['iqiyi', 'trueidshort', 'youtube'], fullPrice: 347, sellingPrice: 229 },
  { id: 'offerGroup69', packName: 'Pack 2', services: ['oned', 'trueplus', 'netflix-mobile'], fullPrice: 357, sellingPrice: 229 },
  { id: 'offerGroup70', packName: 'Pack 2', services: ['oned', 'trueplus', 'netflix-basic'], fullPrice: 427, sellingPrice: 229 },
  { id: 'offerGroup71', packName: 'Pack 2', services: ['oned', 'trueplus', 'youtube'], fullPrice: 437, sellingPrice: 229 },
  { id: 'offerGroup72', packName: 'Pack 2', services: ['oned', 'trueidshort', 'netflix-mobile'], fullPrice: 207, sellingPrice: 229 },
  { id: 'offerGroup73', packName: 'Pack 2', services: ['oned', 'trueidshort', 'netflix-basic'], fullPrice: 277, sellingPrice: 229 },
  { id: 'offerGroup74', packName: 'Pack 2', services: ['oned', 'trueidshort', 'youtube'], fullPrice: 287, sellingPrice: 229 },
  { id: 'offerGroup75', packName: 'Pack 2', services: ['trueplus', 'trueidshort', 'netflix-mobile'], fullPrice: 347, sellingPrice: 229 },
  { id: 'offerGroup76', packName: 'Pack 2', services: ['trueplus', 'trueidshort', 'netflix-basic'], fullPrice: 417, sellingPrice: 229 },
  { id: 'offerGroup77', packName: 'Pack 2', services: ['trueplus', 'trueidshort', 'youtube'], fullPrice: 427, sellingPrice: 229 },

  // Pack3 - 4 services - 339 THB
  { id: 'offerGroup78', packName: 'Pack 3', services: ['viu', 'wetv', 'netflix-mobile', 'youtube'], fullPrice: 536, sellingPrice: 339 },
  { id: 'offerGroup79', packName: 'Pack 3', services: ['viu', 'wetv', 'netflix-basic', 'youtube'], fullPrice: 606, sellingPrice: 339 },
  { id: 'offerGroup80', packName: 'Pack 3', services: ['viu', 'iqiyi', 'netflix-mobile', 'youtube'], fullPrice: 516, sellingPrice: 339 },
  { id: 'offerGroup81', packName: 'Pack 3', services: ['viu', 'iqiyi', 'netflix-basic', 'youtube'], fullPrice: 586, sellingPrice: 339 },
  { id: 'offerGroup82', packName: 'Pack 3', services: ['viu', 'oned', 'netflix-mobile', 'youtube'], fullPrice: 456, sellingPrice: 339 },
  { id: 'offerGroup83', packName: 'Pack 3', services: ['viu', 'oned', 'netflix-basic', 'youtube'], fullPrice: 526, sellingPrice: 339 },
  { id: 'offerGroup84', packName: 'Pack 3', services: ['viu', 'trueplus', 'netflix-mobile', 'youtube'], fullPrice: 596, sellingPrice: 339 },
  { id: 'offerGroup85', packName: 'Pack 3', services: ['viu', 'trueplus', 'netflix-basic', 'youtube'], fullPrice: 666, sellingPrice: 339 },
  { id: 'offerGroup86', packName: 'Pack 3', services: ['viu', 'trueidshort', 'netflix-mobile', 'youtube'], fullPrice: 446, sellingPrice: 339 },
  { id: 'offerGroup87', packName: 'Pack 3', services: ['viu', 'trueidshort', 'netflix-basic', 'youtube'], fullPrice: 516, sellingPrice: 339 },
  { id: 'offerGroup88', packName: 'Pack 3', services: ['wetv', 'iqiyi', 'netflix-mobile', 'youtube'], fullPrice: 536, sellingPrice: 339 },
  { id: 'offerGroup89', packName: 'Pack 3', services: ['wetv', 'iqiyi', 'netflix-basic', 'youtube'], fullPrice: 606, sellingPrice: 339 },
  { id: 'offerGroup90', packName: 'Pack 3', services: ['wetv', 'oned', 'netflix-mobile', 'youtube'], fullPrice: 476, sellingPrice: 339 },
  { id: 'offerGroup91', packName: 'Pack 3', services: ['wetv', 'oned', 'netflix-basic', 'youtube'], fullPrice: 546, sellingPrice: 339 },
  { id: 'offerGroup92', packName: 'Pack 3', services: ['wetv', 'trueplus', 'netflix-mobile', 'youtube'], fullPrice: 616, sellingPrice: 339 },
  { id: 'offerGroup93', packName: 'Pack 3', services: ['wetv', 'trueplus', 'netflix-basic', 'youtube'], fullPrice: 686, sellingPrice: 339 },
  { id: 'offerGroup94', packName: 'Pack 3', services: ['wetv', 'trueidshort', 'netflix-mobile', 'youtube'], fullPrice: 466, sellingPrice: 339 },
  { id: 'offerGroup95', packName: 'Pack 3', services: ['wetv', 'trueidshort', 'netflix-basic', 'youtube'], fullPrice: 536, sellingPrice: 339 },
  { id: 'offerGroup96', packName: 'Pack 3', services: ['iqiyi', 'oned', 'netflix-mobile', 'youtube'], fullPrice: 456, sellingPrice: 339 },
  { id: 'offerGroup97', packName: 'Pack 3', services: ['iqiyi', 'oned', 'netflix-basic', 'youtube'], fullPrice: 526, sellingPrice: 339 },
  { id: 'offerGroup98', packName: 'Pack 3', services: ['iqiyi', 'trueplus', 'netflix-mobile', 'youtube'], fullPrice: 596, sellingPrice: 339 },
  { id: 'offerGroup99', packName: 'Pack 3', services: ['iqiyi', 'trueplus', 'netflix-basic', 'youtube'], fullPrice: 666, sellingPrice: 339 },
  { id: 'offerGroup100', packName: 'Pack 3', services: ['iqiyi', 'trueidshort', 'netflix-mobile', 'youtube'], fullPrice: 446, sellingPrice: 339 },
  { id: 'offerGroup101', packName: 'Pack 3', services: ['iqiyi', 'trueidshort', 'netflix-basic', 'youtube'], fullPrice: 516, sellingPrice: 339 },
  { id: 'offerGroup102', packName: 'Pack 3', services: ['oned', 'trueplus', 'netflix-mobile', 'youtube'], fullPrice: 536, sellingPrice: 339 },
  { id: 'offerGroup103', packName: 'Pack 3', services: ['oned', 'trueplus', 'netflix-basic', 'youtube'], fullPrice: 606, sellingPrice: 339 },
  { id: 'offerGroup104', packName: 'Pack 3', services: ['oned', 'trueidshort', 'netflix-mobile', 'youtube'], fullPrice: 386, sellingPrice: 339 },
  { id: 'offerGroup105', packName: 'Pack 3', services: ['oned', 'trueidshort', 'netflix-basic', 'youtube'], fullPrice: 456, sellingPrice: 339 },
  { id: 'offerGroup106', packName: 'Pack 3', services: ['trueplus', 'trueidshort', 'netflix-mobile', 'youtube'], fullPrice: 526, sellingPrice: 339 },
  { id: 'offerGroup107', packName: 'Pack 3', services: ['trueplus', 'trueidshort', 'netflix-basic', 'youtube'], fullPrice: 596, sellingPrice: 339 },

  // Pack4 - 4 services - 449 THB
  { id: 'offerGroup108', packName: 'Pack 4', services: ['viu', 'wetv', 'iqiyi', 'netflix-standard'], fullPrice: 726, sellingPrice: 449 },
  { id: 'offerGroup109', packName: 'Pack 4', services: ['viu', 'wetv', 'iqiyi', 'netflix-premium'], fullPrice: 796, sellingPrice: 449 },
  { id: 'offerGroup110', packName: 'Pack 4', services: ['viu', 'wetv', 'iqiyi', 'youtube'], fullPrice: 556, sellingPrice: 449 },
  { id: 'offerGroup111', packName: 'Pack 4', services: ['viu', 'wetv', 'oned', 'netflix-standard'], fullPrice: 666, sellingPrice: 449 },
  { id: 'offerGroup112', packName: 'Pack 4', services: ['viu', 'wetv', 'oned', 'netflix-premium'], fullPrice: 736, sellingPrice: 449 },
  { id: 'offerGroup113', packName: 'Pack 4', services: ['viu', 'wetv', 'oned', 'youtube'], fullPrice: 496, sellingPrice: 449 },
  { id: 'offerGroup114', packName: 'Pack 4', services: ['viu', 'wetv', 'trueplus', 'netflix-standard'], fullPrice: 806, sellingPrice: 449 },
  { id: 'offerGroup115', packName: 'Pack 4', services: ['viu', 'wetv', 'trueplus', 'netflix-premium'], fullPrice: 876, sellingPrice: 449 },
  { id: 'offerGroup116', packName: 'Pack 4', services: ['viu', 'wetv', 'trueplus', 'youtube'], fullPrice: 636, sellingPrice: 449 },
  { id: 'offerGroup117', packName: 'Pack 4', services: ['viu', 'wetv', 'trueidshort', 'netflix-standard'], fullPrice: 656, sellingPrice: 449 },
  { id: 'offerGroup118', packName: 'Pack 4', services: ['viu', 'wetv', 'trueidshort', 'netflix-premium'], fullPrice: 726, sellingPrice: 449 },
  { id: 'offerGroup119', packName: 'Pack 4', services: ['viu', 'wetv', 'trueidshort', 'youtube'], fullPrice: 486, sellingPrice: 449 },
  { id: 'offerGroup120', packName: 'Pack 4', services: ['viu', 'iqiyi', 'oned', 'netflix-standard'], fullPrice: 646, sellingPrice: 449 },
  { id: 'offerGroup121', packName: 'Pack 4', services: ['viu', 'iqiyi', 'oned', 'netflix-premium'], fullPrice: 716, sellingPrice: 449 },
  { id: 'offerGroup122', packName: 'Pack 4', services: ['viu', 'iqiyi', 'oned', 'youtube'], fullPrice: 476, sellingPrice: 449 },
  { id: 'offerGroup123', packName: 'Pack 4', services: ['viu', 'iqiyi', 'trueplus', 'netflix-standard'], fullPrice: 786, sellingPrice: 449 },
  { id: 'offerGroup124', packName: 'Pack 4', services: ['viu', 'iqiyi', 'trueplus', 'netflix-premium'], fullPrice: 856, sellingPrice: 449 },
  { id: 'offerGroup125', packName: 'Pack 4', services: ['viu', 'iqiyi', 'trueplus', 'youtube'], fullPrice: 616, sellingPrice: 449 },
  { id: 'offerGroup126', packName: 'Pack 4', services: ['viu', 'iqiyi', 'trueidshort', 'netflix-standard'], fullPrice: 636, sellingPrice: 449 },
  { id: 'offerGroup127', packName: 'Pack 4', services: ['viu', 'iqiyi', 'trueidshort', 'netflix-premium'], fullPrice: 706, sellingPrice: 449 },
  { id: 'offerGroup128', packName: 'Pack 4', services: ['viu', 'iqiyi', 'trueidshort', 'youtube'], fullPrice: 466, sellingPrice: 449 },
  { id: 'offerGroup129', packName: 'Pack 4', services: ['viu', 'oned', 'trueplus', 'netflix-standard'], fullPrice: 726, sellingPrice: 449 },
  { id: 'offerGroup130', packName: 'Pack 4', services: ['viu', 'oned', 'trueplus', 'netflix-premium'], fullPrice: 796, sellingPrice: 449 },
  { id: 'offerGroup131', packName: 'Pack 4', services: ['viu', 'oned', 'trueplus', 'youtube'], fullPrice: 556, sellingPrice: 449 },
  { id: 'offerGroup132', packName: 'Pack 4', services: ['viu', 'oned', 'trueidshort', 'netflix-standard'], fullPrice: 576, sellingPrice: 449 },
  { id: 'offerGroup133', packName: 'Pack 4', services: ['viu', 'oned', 'trueidshort', 'netflix-premium'], fullPrice: 646, sellingPrice: 449 },
  { id: 'offerGroup134', packName: 'Pack 4', services: ['viu', 'oned', 'trueidshort', 'youtube'], fullPrice: 406, sellingPrice: 449 },
  { id: 'offerGroup135', packName: 'Pack 4', services: ['viu', 'trueplus', 'trueidshort', 'netflix-standard'], fullPrice: 716, sellingPrice: 449 },
  { id: 'offerGroup136', packName: 'Pack 4', services: ['viu', 'trueplus', 'trueidshort', 'netflix-premium'], fullPrice: 786, sellingPrice: 449 },
  { id: 'offerGroup137', packName: 'Pack 4', services: ['viu', 'trueplus', 'trueidshort', 'youtube'], fullPrice: 546, sellingPrice: 449 },
  { id: 'offerGroup138', packName: 'Pack 4', services: ['wetv', 'iqiyi', 'oned', 'netflix-standard'], fullPrice: 666, sellingPrice: 449 },
  { id: 'offerGroup139', packName: 'Pack 4', services: ['wetv', 'iqiyi', 'oned', 'netflix-premium'], fullPrice: 736, sellingPrice: 449 },
  { id: 'offerGroup140', packName: 'Pack 4', services: ['wetv', 'iqiyi', 'oned', 'youtube'], fullPrice: 496, sellingPrice: 449 },
  { id: 'offerGroup141', packName: 'Pack 4', services: ['wetv', 'iqiyi', 'trueplus', 'netflix-standard'], fullPrice: 806, sellingPrice: 449 },
  { id: 'offerGroup142', packName: 'Pack 4', services: ['wetv', 'iqiyi', 'trueplus', 'netflix-premium'], fullPrice: 876, sellingPrice: 449 },
  { id: 'offerGroup143', packName: 'Pack 4', services: ['wetv', 'iqiyi', 'trueplus', 'youtube'], fullPrice: 636, sellingPrice: 449 },
  { id: 'offerGroup144', packName: 'Pack 4', services: ['wetv', 'iqiyi', 'trueidshort', 'netflix-standard'], fullPrice: 656, sellingPrice: 449 },
  { id: 'offerGroup145', packName: 'Pack 4', services: ['wetv', 'iqiyi', 'trueidshort', 'netflix-premium'], fullPrice: 726, sellingPrice: 449 },
  { id: 'offerGroup146', packName: 'Pack 4', services: ['wetv', 'iqiyi', 'trueidshort', 'youtube'], fullPrice: 486, sellingPrice: 449 },
  { id: 'offerGroup147', packName: 'Pack 4', services: ['wetv', 'oned', 'trueplus', 'netflix-standard'], fullPrice: 746, sellingPrice: 449 },
  { id: 'offerGroup148', packName: 'Pack 4', services: ['wetv', 'oned', 'trueplus', 'netflix-premium'], fullPrice: 816, sellingPrice: 449 },
  { id: 'offerGroup149', packName: 'Pack 4', services: ['wetv', 'oned', 'trueplus', 'youtube'], fullPrice: 576, sellingPrice: 449 },
  { id: 'offerGroup150', packName: 'Pack 4', services: ['wetv', 'oned', 'trueidshort', 'netflix-standard'], fullPrice: 596, sellingPrice: 449 },
  { id: 'offerGroup151', packName: 'Pack 4', services: ['wetv', 'oned', 'trueidshort', 'netflix-premium'], fullPrice: 666, sellingPrice: 449 },
  { id: 'offerGroup152', packName: 'Pack 4', services: ['wetv', 'oned', 'trueidshort', 'youtube'], fullPrice: 426, sellingPrice: 449 },
  { id: 'offerGroup153', packName: 'Pack 4', services: ['wetv', 'trueplus', 'trueidshort', 'netflix-standard'], fullPrice: 736, sellingPrice: 449 },
  { id: 'offerGroup154', packName: 'Pack 4', services: ['wetv', 'trueplus', 'trueidshort', 'netflix-premium'], fullPrice: 806, sellingPrice: 449 },
  { id: 'offerGroup155', packName: 'Pack 4', services: ['wetv', 'trueplus', 'trueidshort', 'youtube'], fullPrice: 566, sellingPrice: 449 },
  { id: 'offerGroup156', packName: 'Pack 4', services: ['iqiyi', 'oned', 'trueplus', 'netflix-standard'], fullPrice: 726, sellingPrice: 449 },
  { id: 'offerGroup157', packName: 'Pack 4', services: ['iqiyi', 'oned', 'trueplus', 'netflix-premium'], fullPrice: 796, sellingPrice: 449 },
  { id: 'offerGroup158', packName: 'Pack 4', services: ['iqiyi', 'oned', 'trueplus', 'youtube'], fullPrice: 556, sellingPrice: 449 },
  { id: 'offerGroup159', packName: 'Pack 4', services: ['iqiyi', 'oned', 'trueidshort', 'netflix-standard'], fullPrice: 576, sellingPrice: 449 },
  { id: 'offerGroup160', packName: 'Pack 4', services: ['iqiyi', 'oned', 'trueidshort', 'netflix-premium'], fullPrice: 646, sellingPrice: 449 },
  { id: 'offerGroup161', packName: 'Pack 4', services: ['iqiyi', 'oned', 'trueidshort', 'youtube'], fullPrice: 406, sellingPrice: 449 },
  { id: 'offerGroup162', packName: 'Pack 4', services: ['iqiyi', 'trueplus', 'trueidshort', 'netflix-standard'], fullPrice: 716, sellingPrice: 449 },
  { id: 'offerGroup163', packName: 'Pack 4', services: ['iqiyi', 'trueplus', 'trueidshort', 'netflix-premium'], fullPrice: 786, sellingPrice: 449 },
  { id: 'offerGroup164', packName: 'Pack 4', services: ['iqiyi', 'trueplus', 'trueidshort', 'youtube'], fullPrice: 546, sellingPrice: 449 },
  { id: 'offerGroup165', packName: 'Pack 4', services: ['oned', 'trueplus', 'trueidshort', 'netflix-standard'], fullPrice: 656, sellingPrice: 449 },
  { id: 'offerGroup166', packName: 'Pack 4', services: ['oned', 'trueplus', 'trueidshort', 'netflix-premium'], fullPrice: 726, sellingPrice: 449 },
  { id: 'offerGroup167', packName: 'Pack 4', services: ['oned', 'trueplus', 'trueidshort', 'youtube'], fullPrice: 486, sellingPrice: 449 },

  // Pack5 - 3 services - 559 THB
  { id: 'offerGroup168', packName: 'Pack 5', services: ['viu', 'netflix-standard', 'youtube'], fullPrice: 647, sellingPrice: 559 },
  { id: 'offerGroup169', packName: 'Pack 5', services: ['viu', 'netflix-premium', 'youtube'], fullPrice: 717, sellingPrice: 559 },
  { id: 'offerGroup170', packName: 'Pack 5', services: ['wetv', 'netflix-standard', 'youtube'], fullPrice: 667, sellingPrice: 559 },
  { id: 'offerGroup171', packName: 'Pack 5', services: ['wetv', 'netflix-premium', 'youtube'], fullPrice: 737, sellingPrice: 559 },
  { id: 'offerGroup172', packName: 'Pack 5', services: ['iqiyi', 'netflix-standard', 'youtube'], fullPrice: 647, sellingPrice: 559 },
  { id: 'offerGroup173', packName: 'Pack 5', services: ['iqiyi', 'netflix-premium', 'youtube'], fullPrice: 717, sellingPrice: 559 },
  { id: 'offerGroup174', packName: 'Pack 5', services: ['oned', 'netflix-standard', 'youtube'], fullPrice: 587, sellingPrice: 559 },
  { id: 'offerGroup175', packName: 'Pack 5', services: ['oned', 'netflix-premium', 'youtube'], fullPrice: 657, sellingPrice: 559 },
  { id: 'offerGroup176', packName: 'Pack 5', services: ['trueplus', 'netflix-standard', 'youtube'], fullPrice: 727, sellingPrice: 559 },
  { id: 'offerGroup177', packName: 'Pack 5', services: ['trueplus', 'netflix-premium', 'youtube'], fullPrice: 797, sellingPrice: 559 },
  { id: 'offerGroup178', packName: 'Pack 5', services: ['trueidshort', 'netflix-standard', 'youtube'], fullPrice: 577, sellingPrice: 559 },
  { id: 'offerGroup179', packName: 'Pack 5', services: ['trueidshort', 'netflix-premium', 'youtube'], fullPrice: 647, sellingPrice: 559 },
];

export const userSubscriptions = [
    {
      id: 'sub1',
      serviceName: 'Viu Premium',
      status: 'Active',
      renewalDate: '2024-08-15',
      price: 119,
    },
    {
      id: 'sub2',
      serviceName: 'WeTV VIP',
      status: 'Active',
      renewalDate: '2024-08-22',
      price: 139,
    },
];

export const billingHistory = [
    {
      id: 'bill1',
      date: '2024-07-15',
      description: 'Viu Premium',
      amount: 119,
    },
    {
      id: 'bill2',
      date: '2024-07-22',
      description: 'WeTV VIP',
      amount: 139,
    },
];
